### PR TITLE
New auth

### LINKED ISSUE #50: Nouvelle authentification Hilo
Le 11 avril 2024 Hilo a mis fin à l'authentification par mot de passe. Cette issue va permettre de suivre l'avancement et les bogues en lien avec la nouvelle authentification

### PR DESCRIPTION
**Pull request by SanterreJo**
Closes #50 

<details>
  <summary>📦 Published PR as canary version: <code>2.0.0--canary.48.5ac9481.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install homebridge-hilo@2.0.0--canary.48.5ac9481.0
  # or 
  yarn add homebridge-hilo@2.0.0--canary.48.5ac9481.0
  ```
</details>

### CODE REVIEW

**Comment by tomlaf** [comment]
Good day,

I have appelid the canary release (as the user password does not work anymore), but I'm not able to setup. 
When I click on 'Login with hilo' nothing happend and this is the console error: 
Uncaught (in promise) TypeError: OAuth2Client is not a constructor
    at initiateAuth (index.html?origin=http%3A%2F%2F----SERVEUR URL----%3A8581&v=1.10.0--canary.48.069a029.0:30:18)
    at HTMLButtonElement.onclick (index.html?origin=http%3A%2F%2F----SERVEUR URL----%3A8581&v=1.10.0--canary.48.069a029.0:23:73)
initiateAuth @ index.html?origin=http%3A%2F%2F----SERVEUR URL----%3A8581&v=1.10.0--canary.48.069a029.0:30
onclick @ index.html?origin=http%3A%2F%2F----SERVEUR URL----%3A8581&v=1.10.0--canary.48.069a029.0:23

Any idea ?

**Comment by tomlaf** [comment]
New error, if you are tracking ;-)

Uncaught (in promise) TypeError: r(...).createHash is not a function
    at o (authorization-code.ts:225:29)
    at t.OAuth2AuthorizationCodeClient.getAuthorizeUri (authorization-code.ts:94:29)
    at initiateAuth (index.html?origin=ht….48.eb14910.0:40:54)

**Comment by SanterreJo** [comment]
@tomlaf This a very rough draft of a new implementation for the new authentication flow.

This is still a **Work In Progress** and will not be ready for a release for at least a few days/weeks.

The latest version "works" but the flow isn't documented. So you may try it on your own. I will not try to document or support this flow for now.

**Comment by tomlaf** [comment]
Good day,

I suspect I'm still missing something as I get this error, when I click on "Login wiht HELO" : 

index.html?origin=ht…ary.48.437a1ff.0:75 
 Uncaught (in promise) TypeError: r(...).createHash is not a function
    at o (authorization-code.ts:225:29)
    at t.OAuth2AuthorizationCodeClient.getAuthorizeUri (authorization-code.ts:94:29)
    at initiateAuth (index.html?origin=ht….48.437a1ff.0:52:41)

**Comment by flovilmart** [comment]
Thanks for this! Gave it a spin: 

Running inside my syno DSM as a docker container is a pain to get port forwarding right etc… I ended up gathering the refresh token from a node REPL and it just worked. 
Perhaps we can also consider simply pasting the redirect URL that contains the « code » param inside the config, and to the code <-> refresh token exchange as such?

**Comment by SanterreJo** [comment]
@tomlaf can you confirm that the latest build works for you?

**Comment by tomlaf** [comment]
Good night. 

Confirm all is good to go.

**Pull request merged**
